var ERROR_MESSAGE_EMAIL;
(function (ERROR_MESSAGE_EMAIL) {
    ERROR_MESSAGE_EMAIL["DUPLICATION_ERROR"] = "Already token \uD83D\uDC31\u200D\uD83C\uDFCD";
    ERROR_MESSAGE_EMAIL["EMAIL_NOT_LONG_ENOUGH"] = "Email must be at least 7 character \uD83E\uDD37\u200D\u2640\uFE0F";
    ERROR_MESSAGE_EMAIL["EMAIL_IS_Required"] = " please Enter email \uD83D\uDE12is Required";
})(ERROR_MESSAGE_EMAIL || (ERROR_MESSAGE_EMAIL = {}));
var ERROR_MESSAGE_PASSWORD;
(function (ERROR_MESSAGE_PASSWORD) {
    ERROR_MESSAGE_PASSWORD["PASSWORD_NOT_LONG_ENOUGH"] = "Password must be at least 7 character \uD83E\uDD37\u200D\u2640\uFE0F";
    ERROR_MESSAGE_PASSWORD["PASSWORD_NOT_MATCH"] = "Password not match with compare \uD83D\uDE1C";
})(ERROR_MESSAGE_PASSWORD || (ERROR_MESSAGE_PASSWORD = {}));
var ERROR_MESSAGE_NAME;
(function (ERROR_MESSAGE_NAME) {
    ERROR_MESSAGE_NAME["NAME_NOT_LONG_ENOUGH"] = "Name must be at least 7 character \uD83E\uDD37\u200D\u2640\uFE0F";
    ERROR_MESSAGE_NAME["NAME_NOT_MATCH"] = "name not match with compare \uD83D\uDE1C";
})(ERROR_MESSAGE_NAME || (ERROR_MESSAGE_NAME = {}));
var ERROR_MESSAGE_CATAGORYS;
(function (ERROR_MESSAGE_CATAGORYS) {
    ERROR_MESSAGE_CATAGORYS["NAME_NOT_LONG_ENOUGH"] = "Name must be at least 7 character \uD83E\uDD37\u200D\u2640\uFE0F";
    ERROR_MESSAGE_CATAGORYS["NAME_NOT_MATCH"] = "name not match with compare \uD83D\uDE1C";
})(ERROR_MESSAGE_CATAGORYS || (ERROR_MESSAGE_CATAGORYS = {}));
export { ERROR_MESSAGE_EMAIL, ERROR_MESSAGE_PASSWORD };
